apiVersion: v1
kind: Service
metadata:
  name: nginx-controller-service
  labels:
    app: nginx-controller
spec:
  type: LoadBalancer
  selector:
    app: nginx-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80